apiVersion: apps/v1
kind: Deployment
metadata:
  name: gengoreader
  labels:
    app: gengoreader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gengoreader
  template:
    metadata:
      labels:
        app: gengoreader
    spec:
      containers:
        - name: gengoreader
          image: gronk0770/gengoreader:latest
          imagePullPolicy: IfNotPresent
          env:
            - valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: username
              name: EMAIL
            - valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: password
              name: PASSWORD
# A secrets yaml file of the following format is required. Items in brackets must be replaced with respective values.
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-basic-auth
# type: kubernetes.io/basic-auth
# stringData:
#   username: [EMAIL]
#   password: [PASSWORD/API KEY]
