apiVersion: apps/v1
kind: Deployment
metadata:
  name: gengoreader
  labels:
    app: gengoreader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gengoreader
  template:
    metadata:
      labels:
        app: gengoreader
    spec:
      containers:
        - name: gengoreader
          image: gronk0770/gengoreader:latest
          imagePullPolicy: IfNotPresent
          env:
            - valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: username
              name: EMAIL
            - valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: password
              name: PASSWORD
